spring.application.name=spy-game
spring.datasource.url=jdbc:postgresql://ep-broad-sound-an2bkyr2-pooler.c-6.us-east-1.aws.neon.tech/spygame?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_EPo1BlRSMsQ5

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

